# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f5c0ea3f1c78873ddf0ad6dcdb48d262769a7e98d5492947a529e2b04f276cf47cda8c09d55ab3f55d573bd9d34c0bcf8b1ebfef5b94349c2c860e08cd6bec3

test:
  secret_key_base: f15e434b234ece33b95d6cb2eaabd4832bef9b9d0a484f0167fe8df0ec426e07ade77926bb5ad32e8b4ee54732a2b7d5fe1ce29018dae04bdda9ea98b46f8a8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
